const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const templateSchema = new Schema({
  user_id: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
  planName: String,
  numberOfDays: Number,
  type: String,
  ref:Boolean,
  day1: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day2: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day3: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day4: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day5: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day6: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day7: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day8: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day9: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
day10: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day11: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day12: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day13: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }],
  day14: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day15: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day16: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day17: [{
    name: String,
    set1goal: Number,
    set1reps: Number,
    set1weight: Number,
    set2goal: Number,
    set2reps: Number,
    set2weight: Number,
    set3goal: Number,
    set3reps: Number,
    set3weight: Number
  }],
  day18: [{
  name: String,
  set1goal: Number,
  set1reps: Number,
  set1weight: Number,
  set2goal: Number,
  set2reps: Number,
  set2weight: Number,
  set3goal: Number,
  set3reps: Number,
  set3weight: Number
  }]
})

const Template = mongoose.model('Template', templateSchema);
module.exports = Template;